version: '3'
services:
    postgres-jobz:
        image: postgres
        restart: on-failure
        environment:
            - POSTGRES_DB=jobz
            - POSTGRES_USER=postgresdocker
            - POSTGRES_PASSWORD=1234567890
        # volumes:
        #     - ./postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - tetcha
    # client-jobz:
    #     image: jobz
    #     ports:
    #         - 3000:3000
    #     networks:
    #         - tetcha
networks:
    tetcha:
        external: true
